### ISSUE TITLE
Tier Updates: Visit object changes

### ISSUE THREAD

**Issue by renell-carpenter** [Ready-Ready/HealthySteps_Salesforce#49]
- [x] Add “Exit Program” picklist value to Visit Tier Level; Add only to the Consented Visit record type.
- [x] Add “Exit Reason” (separate issue #20 already in progress) 
- [x] Add “Other Exit Reason” text field (separate issue #21 already in progress)
- [x] Add Field Dependency - Controlling Field: Visit Tier Level, Dependent Field: Exit Reason. Include all Exit Reasons ONLY for "Exit Program"
- [x] Add Validation Rule - Please enter "Exit Reason" if the "Visit Tier Level" is "Exit Program". Display next to "Exit Reason"
- [x] Delete "Tier_Level_and_Status_Must_Align" Validation Rule
- [x] Add “Legacy Tier” picklist field (values: Tier 2, Tier 3); default to "Tier 2"; assign to both visit record types; FLS same as other fields; Place on Consented Visit Layout only, Editable, under "Declined Tier 3" field
- [x] Add “New Tier Entry” checkbox; default to FALSE; FLS same as other fields; Place on BOTH Visit Layouts, Editable, under  “Other Exit Reason”
- [x] Relabel “Tier Level Status” field as "xTier Level Status” and remove from page layout and Child's Visit related list. It can be deleted after the data patch for "Enter New Tier" checkbox is completed (see data patch issue #52)
- [x] Delete “Tier Exit Date” field
